'use client';

import Image from 'next/image';

/**
 * Upper half of the hero stack, painted over the wordmark.
 *
 * The figure is repeated here as an alpha cutout (herobg-fg.png, generated by
 * scripts/build-hero-matte.mjs) so the statue occludes the name — the type
 * passes behind the head instead of across it. Because the cutout covers the
 * type wherever the figure is, the wordmark needs no blend mode to stay
 * legible: it only ever shows against the black plate.
 *
 * Vignette, scanlines and the bottom fade live here rather than in
 * <HeroBackground> so they grade the cutout too; sitting below it, they would
 * have been erased everywhere the figure is repainted.
 */
export default function HeroForeground() {
  return (
    <div className="hero-fg" aria-hidden="true">
      <div className="hero-figure hero-fg-figure">
        <Image
          src="/images/herobg-fg.png"
          alt=""
          fill
          sizes="100vw"
          loading="eager"
          fetchPriority="high"
          className="hero-figure-img"
        />
      </div>

      {/* Pulls the eye to the centre and keeps the corner HUD readable */}
      <div className="hero-bg-vignette" />

      {/* A whisper of texture over the flat black */}
      <div className="hero-bg-scan" />

      {/* Grounds the figure and keeps the cream HUD row on solid black */}
      <div className="hero-bg-fade" />
    </div>
  );
}
